# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Shop Inventory"
client_id = "ddd5645722003fb0b02e3c7200ab7af3"
application_url = "https://0e3a-194-31-212-75.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://0e3a-194-31-212-75.ngrok-free.app/auth/callback",
  "https://0e3a-194-31-212-75.ngrok-free.app/auth/shopify/callback",
  "https://0e3a-194-31-212-75.ngrok-free.app/api/auth/callback",
  "https://0e3a-194-31-212-75.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shop-inventory-prod.myshopify.com"
